### ISSUE TITLE
MIME type for .mjs

### ISSUE THREAD

**Issue by adamduncan** [ceph/ceph.io#101]
We're bundling client-side scripts for the site in both legacy and modern module (`.mjs`) formats.

Can we please add a mime type for `.mjs` files: `text/javascript`

> Your web server needs to be configured to serve .mjs files with the `Content-Type` header `text/javascript`. If your browser is failing to load your .mjs files, that may be why. ([ref](https://philipwalton.com/articles/deploying-es2015-code-in-production-today/#important-considerations))

**Comment by djgalloway** [comment]
Is there a page I can go to to see the error or problem?

**Comment by adamduncan** [comment]
Any page on the develop site should exhibit the warning: https://develop.ceph.io/en-GB/

<img width="1792" alt="Screenshot 2021-03-10 at 18 52 24" src="https://user-images.githubusercontent.com/2671053/110681509-d06ec380-81d1-11eb-97db-4cc5b3ff03f4.png">

We notice the JS enhancements (e.g. the header bar on the homepage should switch to a white background on scroll) aren't functioning, because the file response is empty. 

Thanks

**Comment by djgalloway** [comment]
https://github.com/ceph/ceph.io/pull/106/commits/b4fe2f8256dfe24987748e4773e339d01866a918
