### ISSUE TITLE
CSP for YouTube embeds

### ISSUE THREAD

**Issue by adamduncan** [ceph/ceph.io#102]
Noticing a CSP issue with the YouTube embeds on the Meetups page: https://develop.ceph.io/en-GB/community/meetups/

<img width="534" alt="Screenshot 2021-03-10 at 18 31 08" src="https://user-images.githubusercontent.com/2671053/110679032-e9c24080-81ce-11eb-8561-c17654bce393.png">

Can we please whitelist youtube.com?

**Comment by djgalloway** [comment]
https://github.com/ceph/ceph.io/pull/105
