### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by adamduncan** [ceph/ceph.io#103]
To configure, based on where we permalink our language-specific 404 pages. TBC

**Comment by Pete-Robelou** [comment]
As each 404 would be language specific we're thinking something like this:

```
/en-GB/404.html
```

or 
```
/en-GB/404/index.html
```

@djgalloway Do you have a preference where we permalink the 404 page?

**Comment by adamduncan** [comment]
Hey @djgalloway, can we please get your take on this? We have the page ready but are unsure where to best output it. Imagine it'll need some server configuration to point to the correct when a page isn't found. E.g. https://develop.ceph.io/no-page-here

**Comment by djgalloway** [comment]
Oh, sorry.  Missed that first ping.  Let me play around.

**Comment by djgalloway** [comment]
I like this approach: https://stackoverflow.com/a/43392815/6225562

Let's have a per-language 404.html.  e.g., `/en/404.html`

**Comment by djgalloway** [comment]
I've already pushed [this](https://github.com/ceph/ceph.io/pull/142) code to beta.ceph.io.  Just need the actual 404.html files in place.

**Comment by Pete-Robelou** [comment]
> I've already pushed [this](https://github.com/ceph/ceph.io/pull/142) code to beta.ceph.io. Just need the actual 404.html files in place.

Great, thanks.

@adamduncan I've created the 404.html pages in the correct location. There's a [PR](https://github.com/ceph/ceph.io/pull/145) ready for review.
