### ISSUE TITLE
Gzip static resources

### ISSUE THREAD

**Issue by adamduncan** [ceph/ceph.io#104]
Keen to get some thoughts from the server-side.

Is it possible to serve our static resources (especially `text/css` and `text/javascript` with Gzip compression?

We could see some really effective performance improvements on this front: https://www.webpagetest.org/performance_optimization.php?test=210310_Ai74_0b3ca30afa6828badd8994e5f6bc1e31&run=3#compress_text

Is that easier said than done? 😄

**Comment by djgalloway** [comment]
https://github.com/ceph/ceph.io/pull/106/commits/56715ec713ff916de4abaf71b1acc3cc2b8f2ddb

**Comment by adamduncan** [comment]
Confirm static CSS + JS assets being gzipped at develop.ceph.io. Thank you
