### ISSUE TITLE
Articles: Fallback images

### ISSUE THREAD

**Issue by Pete-Robelou** [ceph/ceph.io#117]
A lot of legacy articles won't have hero images so when they appear on the blog listing page their card will be missing an image. Our current solution checks if an image exists in the frontmatter, if not it is replaced with a single fallback image. This solution means that all articles without a hero image share the same fallback image. 

We should look into a solution that creates a score for each article, perhaps based on the article title, and matches that score against a pool of generic fallback images. This is better than randomly picking images as it means the articles will consistently show the same fallback image everytime the site runs a new build. We need to make sure we have a large enough pool of fallback images to avoid repetition.

**Comment by adamduncan** [comment]
Yep, nice. Perhaps even using the `date` field to crunch?

**Comment by Pete-Robelou** [comment]
> Yep, nice. Perhaps even using the `date` field to crunch?

Maybe, my only concern with using the date field would be you're more likely to see the same image for articles published on a similar date. It may not look so good on the listing page as you'd see groups of the same image.

**Comment by adamduncan** [comment]
I wonder if we use a clever algorithm to reduce the date's digits down to a single root, we'd have a pretty tidy solution: https://jsbin.com/polidobiqa/edit?js,console,output

(TIL about "casting out nines" 😄)
