### ISSUE TITLE
Amend language site directory names, redirects

### ISSUE THREAD

**Issue by adamduncan** [ceph/ceph.io#122]
The decision's been made to go with two-letter country codes for our language site sub-directories.

- [x] @Pete-Robelou, can we please rename our `en-GB` (and `jp-JP`, for the purposes of demonstration?) directories to their two-letter equivalent? `en` and `jp`, respectively. Expect we'll also need to amend any reference of `en-GB` where used for default/fallback locale, or collection paths, etc.
- [x] @djgalloway Once this has been done, can we please get your support in updating the redirects to reflect the change? If that's just a case of changing redirect references in `/ansible/roles/deploy/templates/site.j2` (?) then @Pete-Robelou, we can manage that as part of our code updates.

In future, should we need region-specific language identifiers for language sites (e.g. `pt-br`), we'll introduce them as necessary, and for those sites only.

**Comment by djgalloway** [comment]
> If that's just a case of changing redirect references in `/ansible/roles/deploy/templates/site.j2` (?) then @Pete-Robelou, we can manage that as part of our code updates.

That's all it should take.  The playbook gets run automatically to update nginx.  I'm happy to help if that doesn't do it for some reason.

**Comment by Pete-Robelou** [comment]
@adamduncan All done.

**Comment by adamduncan** [comment]
Think this one's all good and deployed? Good to close?

**Comment by Pete-Robelou** [comment]
Yeah, all good.
