### ISSUE TITLE
Assets: Unsplash assets

### ISSUE THREAD

**Issue by Pete-Robelou** [ceph/ceph.io#124]
- [x] Replace iStock assets with Unsplash assets

See [google sheet for reference](https://docs.google.com/spreadsheets/d/1HM6g0YDHxaNsBam9wzDPeCrmaW7zR1MKEY2xBuc_1II/edit#gid=0)

**Comment by Pete-Robelou** [comment]
@adamduncan I've updated the assets as per the google sheet.

There weren't that many to swap over as some pages need content. However, I still optimised the suggested assets and added them to the solution so when we have content we can just drop them in.

**Comment by adamduncan** [comment]
Thanks @Pete-Robelou, that's great.

cc @Thingee — this PR adds a bunch of the proposed assets to `/src/assets/bitmaps` for use as more pages build out their content.

**Comment by Thingee** [comment]
Thanks Pete, the latest build looks great!
