### ISSUE TITLE
301 redirects

### ISSUE THREAD

**Issue by adamduncan** [ceph/ceph.io#129]
The existing site has quite a comprehensive set of [XML sitemaps](https://ceph.io/sitemap_index.xml).

We'll want to devise which sections of the site have moved location from the existing IA to the new IA, and which of those would benefit from having 301 redirects in place to improve user experience and search indexing as we migrate.

Have added a [Redirects](https://docs.google.com/spreadsheets/d/1HM6g0YDHxaNsBam9wzDPeCrmaW7zR1MKEY2xBuc_1II/edit#gid=900869262) sheet to get the ball rolling.

---

More context via email:

> We’re looking to ensure that users of the site find their way to relevant new pages, whether they’ve come from an old bookmark or an old link that’s still indexed by a search engine/third-party site. This was captured in the original PRD, and we've since started a conversation over in #139.
> 
> We’ve audited the current site against the new site, and captured page considerations in this Redirects sheet. We’ve made our best guess of what pages we will want to implement 301 redirects for. It seems there are quite a few legacy pages that won’t be on the new site, and likely not needed going forward. 
> 
> What we want to action between 18–22 June:
> - **Mike:** Can you please ensure that all pages that you feel are important to redirect for have a checkmark in the Needed column, and hide any rows you’re confident we won’t need. Have we missed any others?
> - Most redirects are a straight forward 1:1 mapping. Dynamic collections (blogs, see notes may require automation/generalisation based on the differing URL schemes. **Mike**, are they something you’d be able to generate, based on your work with the blog exporter? Or do we put in place a generic redirect for all old blog posts to the new Blog homepage?
> - **David/Duck**: Once this list is finalised, can you please coordinate on implementing the redirects as part of the server config?

**Comment by Pete-Robelou** [comment]
@adamduncan I've been through all the XML sitemaps and updated the Redirects sheet.

There are quite a few pages that don't exist in the new site, I'm not really sure the best plan for resolving these. A second pair of eyes on some of the pages may help.

When it comes to blog posts, press releases etc... I suspect we may want to redirect to the root of the section so `en/news/blog/` . There are way to many articles to redirect them individually and based on the Blog content dump most of them won't exist in the new site.

There are a lot of pages where I couldn't ascertain what part of the site they belong too so I couldn't map them to anything in the new site.

**Comment by adamduncan** [comment]
Thanks @Pete-Robelou. I've updated [the spreadsheet](https://docs.google.com/spreadsheets/d/1HM6g0YDHxaNsBam9wzDPeCrmaW7zR1MKEY2xBuc_1II/edit#gid=900869262) with a few extra notes, and included a checklist so we can determine those redirects that we want to put in place and those which have been put in place.

Added [a comment](https://docs.google.com/spreadsheets/d/1HM6g0YDHxaNsBam9wzDPeCrmaW7zR1MKEY2xBuc_1II/edit?disco=AAAAMgCtJPA) re: the blog re-mapping. Feels worth exploring, as it'd be a shame to lose out on legacy SEO of blog posts.

For those legacy pages that we're unsure of, I've left unticked. I don't expect we'll be needing to recreate nor redirect to some of these older pages. One for the group to decide.

**Comment by djgalloway** [comment]
I've pushed all these to nginx.  Does someone have a fancy way of checking each one of them?

https://github.com/ceph/ceph.io/pull/179

**Comment by adamduncan** [comment]
> I've pushed all these to nginx. Does someone have a fancy way of checking each one of them?

I ran through through [this tool](https://www.rankwatch.com/free-tools/url-Redirect-checker) and captured the results here in [this spreadsheet](https://docs.google.com/spreadsheets/d/1-8KUFTRIEatncSbXQF-R37gmzAHR-e91SkRLI9hw3Ew/edit). Looking good to me

**Comment by adamduncan** [comment]
Sorted with PR #179, thanks @djgalloway
