### ISSUE TITLE
Sitemap xml

### ISSUE THREAD

**Issue by Pete-Robelou** [ceph/ceph.io#136]
- [x] Create sitemap xml

Some references:
- https://github.com/11ty/eleventy-base-blog/blob/master/sitemap.xml.njk
- https://www.npmjs.com/package/@quasibit/eleventy-plugin-sitemap
- https://www.11ty.recipes/recipes/add-a-sitemap/

**Comment by Pete-Robelou** [comment]
@adamduncan I've got the sitemap.xml working now with a unique `translationKey` per page using `eleventyComputed.js`.

I've spotted an issue relating to pages created with `pagination`, they all use the same `href` even though they have different `loc`. I've had a look round and it seems to be a common issue that's not been resolved. https://github.com/11ty/eleventy/issues/248#issuecomment-653754037

It raises the question of whether we need to include category pages in the sitemap.xml as the pages they reference are the ones that matter, `blog-posts`, `case-studies`, `press-releases` etc... It's probably not worth including the blog search page either as on it's own it doesn't contain any content. We can remove this pages with `eleventyExcludeFromCollections: true`, what do you think ?

```
  <url>
    <loc>https://ceph.io/en/discover/case-studies/commerce/</loc>
    <lastmod>2021-06-07T09:59:39.698Z</lastmod>
    <xhtml:link rel="alternate" hreflang="en" href="https://ceph.io/en/discover/case-studies/commerce/" />
  </url>
  <url>
    <loc>https://ceph.io/en/discover/case-studies/government/</loc>
    <lastmod>2021-06-07T09:59:39.698Z</lastmod>
    <xhtml:link rel="alternate" hreflang="en" href="https://ceph.io/en/discover/case-studies/commerce/" />
  </url>
  <url>
    <loc>https://ceph.io/en/discover/case-studies/information/</loc>
    <lastmod>2021-06-07T09:59:39.698Z</lastmod>
    <xhtml:link rel="alternate" hreflang="en" href="https://ceph.io/en/discover/case-studies/commerce/" />
  </url>
```

**Comment by adamduncan** [comment]
Mm, that's unfortunate, but not a show-stopper. Would be nice, I suppose, from an indexing POV for those category pages to be included. But perhaps until that issue is resolved, it's a case of excluding them from the sitemap?

Everything else looking good.

**Comment by Pete-Robelou** [comment]
> Mm, that's unfortunate, but not a show-stopper. Would be nice, I suppose, from an indexing POV for those category pages to be included. But perhaps until that issue is resolved, it's a case of excluding them from the sitemap?
> 
> Everything else looking good.

If we only want to remove them from the sitemap collection we should use a specific tag rather than `eleventyExcludeFromCollections: true` as this excludes them from all collections.

@adamduncan What do you think?

**Comment by adamduncan** [comment]
Sounds okay to me for now, yep
