### ISSUE TITLE
Code formatting and automation

### ISSUE THREAD

**Issue by Pete-Robelou** [ceph/ceph.io#137]
- [x] Update [Prettier](https://www.npmjs.com/package/prettier) to latest version and run `format` script to make consistent.
- [x] Implement [husky](https://www.npmjs.com/package/husky) and [lint-staged](https://www.npmjs.com/package/lint-staged) to ensure files edited are formatted as they make their way into the repo on precommit.

Some references:
- https://codeburst.io/continuous-integration-lint-staged-husky-pre-commit-hook-test-setup-47f8172924fc
- https://www.joshuacolvin.net/git-hooks-with-husky-and-lint-staged/

**Comment by adamduncan** [comment]
@Pete-Robelou On second thoughts here, perhaps we forgo running a sitewide`format` across the codebase. Content contributions are starting to come in, so wouldn't want to create unnecessary conflicts.

Would still suggest we update Prettier and set up `husky` / `lint-staged`, that way files will progressively fall into the pit of formatting success as they're subsequently re-commited over time.

Would be good to run Prettier locally all the same, to gauage how many files would be affected by a blanket reformat.

**Comment by Pete-Robelou** [comment]
Installed latest versions of `husky` and `lint-staged` and also updated `prettier` to the latest.

Configured `lint-staged` and `prettier` to look at the same files `js|json|css|md|html`.
