### ISSUE TITLE
Page: Home

### ISSUE THREAD

**Issue by adamduncan** [ceph/ceph.io#16]
Resources:
- [Design](https://projects.invisionapp.com/share/D8Z2N4X7U6J#/screens/432973993)

**Comment by Pete-Robelou** [comment]
Done.

I've added content from the supplied docs so it can all be reviewed within the context of the design. There's an additional paragraph in the content doc that's not in the design so I've fitted it in the best I could. 

- [ ] Check matrix modules content
- [ ] Check all link locations
- [ ] Replace placeholder images
