### ISSUE TITLE
Collection category filter reset

### ISSUE THREAD

**Issue by adamduncan** [ceph/ceph.io#160]
Currently Blog category filter's first, "empty" option contains the `value="/{{ locale }}/news/blog"`. This serves as a faux-reset, in that it "clears" the current category selection (i.e. returns user to Blog homepage).

We should do the same for other collections with category filters (Press releases, Events, Case studies, ...?)

**Comment by Pete-Robelou** [comment]
Agreed, this is now implemented for all collections with categories.

See #139 for related details.
