### ISSUE TITLE
Run Lighthouse audit to identify any pre-launch low-hanging enhancements

### ISSUE THREAD

**Issue by adamduncan** [ceph/ceph.io#176]

**Comment by Pete-Robelou** [comment]
I've created a `meta description` and updated the `alternate language links` to have a full site URL. This improves the SEO score.

**Comment by Pete-Robelou** [comment]
I've tweaked the lightness of `grey-300` and `red-500` by a tiny, imperceivable amount to make them AA accessible.

Google fonts CSS now loads async so it's no longer a render-block.

**Comment by adamduncan** [comment]
Thanks @Pete-Robelou
