### ISSUE TITLE
Page: Discover / Benefits

### ISSUE THREAD

**Issue by adamduncan** [ceph/ceph.io#18]
Resources:
- [Design](https://projects.invisionapp.com/share/D8Z2N4X7U6J#/screens/432973999)

**Comment by Pete-Robelou** [comment]
Done.

I've added content from the supplied docs so it can all be reviewed within the context of the design. The content doc is a little light in comparison to the design, it doesn't include and stats/figures for the cards, so I've laid them out following the design and filled them with lorem ipsum for now. 

- [ ] Check all link locations
- [ ] Replace placeholder images
- [ ] Check logos for all cards and replace if necessary
- [ ] Replace lorem ipsum
