### ISSUE TITLE
Remove Press release and Planet Ceph sections for launch

### ISSUE THREAD

**Issue by adamduncan** [ceph/ceph.io#181]
- [x] "Releases" posts will be imported into Blog (#174), as per existing site. Not sure we have need for Releases at time of go live
    - For context, was spec'd as: _"Ceph foundation announcements (internal), Major announcements from members"_. Will leave to group to decide if/when it's revived
- [x] Planet Ceph section can go entirely, as also won't have content for launch

**Comment by Pete-Robelou** [comment]
All done.

I also updated the `News` page to remove any links to `Press Releases` or `Planet Ceph`.
