### ISSUE TITLE
Choose fallback placeholder images for Blog posts without images

### ISSUE THREAD

**Issue by adamduncan** [ceph/ceph.io#183]
Legacy blog posts without images will fallback to one of 9 images, based on `getSingleDigitFromDate`.

Note: Currently pulling from set of `/assets/bitmaps/photo-fabric-0x` images. We'll just need `01` to `09`, based on the algorithm.

Need to select 9 appropriate images, any subtle colours/gradients/textures should work best. Suggest we keep their colour palette in line with supplementary colours from the Ceph brand.

Need to get this in prior to launch, as all blog articles at the time of launch will be utilising fallback images:

<img width="1573" alt="Screenshot 2021-06-17 at 15 14 56" src="https://user-images.githubusercontent.com/2671053/122414612-2dbba300-cf7f-11eb-9786-98e1732a6039.png">

**Comment by adamduncan** [comment]
@Thingee Has been collecting some image sets in our [spreadsheet](https://docs.google.com/spreadsheets/d/1HM6g0YDHxaNsBam9wzDPeCrmaW7zR1MKEY2xBuc_1II/edit#gid=986940380) here. Perhaps the [collection of marine textures](https://unsplash.com/photos/g0eRErPBoTA) could be made more subtle and lightly colourized?

**Comment by Pete-Robelou** [comment]
@adamduncan I've used the marine textures to create a new set of 9 assets.

I noticed the `tech talks` on the `community` landing page also needed the fallback treatment so I've implemented the same logic we use for the `blog posts`.
