### ISSUE TITLE
Remove all dummy case studies

### ISSUE THREAD

**Issue by adamduncan** [ceph/ceph.io#188]
Now we've got a couple of real case studies in (#172), let's remove any of the dummy Case study pages/references throughout the site.

**Comment by adamduncan** [comment]
FYI — @fishoutoforder Just a note re: Case study ordering, if you're curious. These are automatically ordered by Creation date. If we need more fine-grained control over their sort order, we'd want to introduce a `date` property to the frontmatter of each case study 👍

**Comment by fishoutoforder** [comment]
@adamduncan regarding sorting by creation date: I'm not sure if this is implemented yet? Because at the moment they're not being ordered that way; they're appearing in reverse alphabetical order (the airforce one was created most recently, the Ceph in a box/openstack ones are the oldest)

**Comment by adamduncan** [comment]
@fishoutoforder You're correct, there was an issue with ordering earlier. This was just corrected a couple of hours ago ([ed6128c4](https://github.com/ceph/ceph.io/pull/206/commits/ed6128c4717df5b4f1a05ff4fa920bcdfa6a5a54?file-filters%5B%5D=.njk)). This should mean Blogs and Case studies are now correctly reverse chronological (based on `date` in frontmatter and file creation date, respectively). See [11ty docs re: dates](https://www.11ty.dev/docs/dates/)

You touched on an interesting point re: files in git environments and build servers. Let's keep an eye on it, but let me know if it's not behaving as expected and we can dive deeper into the specifics 👍

**Comment by fishoutoforder** [comment]
@adamduncan Right, that makes sense, I'd just assumed (incorrectly) that the sort included date **and** time; given all five of the new case studies were created on the same day, the secondary alphabetical sorting makes sense. Not an issue going forward at all.
