### ISSUE TITLE
Shortcode: Subscribe to Ceph Announcements

### ISSUE THREAD

**Issue by Pete-Robelou** [ceph/ceph.io#190]

**Comment by adamduncan** [comment]
Related: https://github.com/ceph/ceph.io/pull/186

Note this has come off a lot of pages now

**Comment by Pete-Robelou** [comment]
> Note this has come off a lot of pages now

I think there's still value in creating a `shortcode` for this. Once #186 has been merged I'll get it done.

@zdover23 Where would you like `Other ways to stay connected` to link to?

Ignore the `lorem ipsum` copy as this is an old screenshot 🙂 

<img width="1035" alt="Screenshot 2021-06-18 at 18 16 33" src="https://user-images.githubusercontent.com/13508865/122596223-73509c80-d061-11eb-954e-8ff8214ad273.png">

**Comment by Pete-Robelou** [comment]
Let's link it to `/en/community/connect/`.

**Comment by adamduncan** [comment]
> Let's link it to /en/community/connect/.

@Pete-Robelou Whether or not we make this a shortcode for launch, we'll still need to link "Other ways to stay connected" text here

**Comment by Pete-Robelou** [comment]
@adamduncan As this only appears on the `/news/` page now there's no point with a `shortcode` or `include`. I've updated the link as discussed above.

**Comment by adamduncan** [comment]
Happy for you to close this in that case
