### ISSUE TITLE
Events: Update content

### ISSUE THREAD

**Issue by Pete-Robelou** [ceph/ceph.io#194]
The Events section is currently using placeholder content. It does however use real content from Events but it was stitched together to test the styling, so none of the Events are real.

- [x] Removed placeholder events
- [x] Update content of one Event to be a real event

**Comment by adamduncan** [comment]
cc @zdover23  Trying to also add a future event here, but may need some support on working with future/unknown dates

**Comment by Pete-Robelou** [comment]
I've removed all the placeholder content and created a genuine `Ceph Day` and `Cephalocon` event. The `Cephalocon` event needed some additional sponsor logos so I've created them and dropped them into the `/assets/bitmaps/` folder.

I've also updated the CSS so anchor headings only appear on blog posts. PurgeCSS was removing the CSS needed for `.link-anchor` so I updated the purgeCSS safe-list.
