### ISSUE TITLE
Remove dummy content in matrix modules, etc.

### ISSUE THREAD

**Issue by adamduncan** [ceph/ceph.io#195]
It's a bit misleading on Homepage (In focus) and Events page.

Make this more obvious this content is not real and needs populating.

**Comment by adamduncan** [comment]
> MD: So to be clear, the whole module would be removed and  the homepage for go live would look like this?
> MP: Yes

Remove matrix module from Homepage. 

Assumed same of Community landing page: https://develop.ceph.io/en/community Will confirm

**Comment by Pete-Robelou** [comment]
@adamduncan Should we also remove them from https://develop.ceph.io/en/news/ as this is all placeholder content?

**Comment by adamduncan** [comment]
> Should we also remove them from https://develop.ceph.io/en/news/ as this is all placeholder content?

Unfortunately, yes. In a future update we should reinstate these. The original intent was to editorially select 3 of the best new Blogs and Press releases. An alternative (more automated, less editorial) solution would be to pull the latest 3 articles through.

For a future update
