### ISSUE TITLE
Lorem ipsum replacement in Discover -> Technology

### ISSUE THREAD

**Issue by fishoutoforder** [ceph/ceph.io#204]
Lorem ipsum placeholders remain on the [Technology page](https://develop.ceph.io/en/discover/technology/) - need replacing with additional content about Ceph's architecture.

**Comment by fishoutoforder** [comment]
(Aware that there was a suggestion to just remove all the additional page content placeholders in #175, however in discussion with Mars re: the launch content requirements, we'd still like to include some additional Ceph architecture information. The intention is that it will make it easier for future contributors post-launch to build on these topics rather than needing to create them from scratch.)

As I'd already written a full page on Ceph's architecture (in #172, though this commit was revoked due to conflicts with #175) this is not an issue for me to turn around today.

**Comment by Pete-Robelou** [comment]
@fishoutoforder I've updated the spacing on this page and merged the PR. Are you happy for this this ticket to be closed?

**Comment by fishoutoforder** [comment]
@Pete-Robelou cheers, that's perfect - will now close.
