### ISSUE TITLE
Sort Case studies reverse chronological

### ISSUE THREAD

**Issue by adamduncan** [ceph/ceph.io#207]
More real case studies coming in now (e.g. https://doc-188-case-study-cleanup.ceph.io/en/discover/case-studies/).

Notice they're being sorted reverse chonologically in "Recent case studies" on the Discover landing page (https://doc-188-case-study-cleanup.ceph.io/en/discover/), but chronologically on the actual Case studies listing page (https://doc-188-case-study-cleanup.ceph.io/en/discover/case-studies/)

**Comment by adamduncan** [comment]
Think this was fixed with https://github.com/ceph/ceph.io/pull/206/commits/ed6128c4717df5b4f1a05ff4fa920bcdfa6a5a54 and merged with #206, @Pete-Robelou?

**Comment by Pete-Robelou** [comment]
> Think this was fixed with [ed6128c](https://github.com/ceph/ceph.io/commit/ed6128c4717df5b4f1a05ff4fa920bcdfa6a5a54) and merged with #206, @Pete-Robelou?

Yeah, this is all fixed now.
