### ISSUE TITLE
Lorem ipsum in Discover module

### ISSUE THREAD

**Issue by fishoutoforder** [ceph/ceph.io#214]
Just been brought to my attention that there is a "discover more" module appended to each individual case study page, [for example, this one](https://develop.ceph.io/en/discover/case-studies/minnesota-supercomputing-institute/) which is currently still lorem ipsum text.

@Pete-Robelou or @adamduncan I believe the case study page layout is determined by `\_includes\layouts\case-study.njk` - I'm happy to edit the lorem ispum within this .njk file, but can I double-check that this is the only file I'd need to alter?

**Comment by fishoutoforder** [comment]
I am now closing this as it appears @Pete-Robelou beat me to this by two minutes - this issue is a duplicate of #213

**Comment by Pete-Robelou** [comment]
> I am now closing this as it appears @Pete-Robelou beat me to this by two minutes - this issue is a duplicate of #213

Ha, yeah. I literally just created a ticket 🙂
