### ISSUE TITLE
Page: Solutions

### ISSUE THREAD

**Issue by adamduncan** [ceph/ceph.io#22]
Resources:
- [Design](https://projects.invisionapp.com/share/D8Z2N4X7U6J#/screens/432973995)

**Comment by Pete-Robelou** [comment]
Done.

I've added content from the supplied docs so it can all be reviewed within the context of the design. There was an additional section of content not shown on the design so I've incorporated it based on a 3 card layout as seen on the `Discover` page.

The content for `Training & professional services` is a bit light in comparison to the design. Do we need more content here?

- [ ] Check all link locations
- [ ] Need billboard image
- [ ] Check logos for `Case studies` and replace if necessary
- [ ] Resolve images for `Browse more case studies` categories.
