### ISSUE TITLE
Minify HTML

### ISSUE THREAD

**Issue by adamduncan** [ceph/ceph.io#220]
Minify all HTML output files as part of 11ty build config.

E.g. from [this reference](https://mattclaffey.medium.com/how-to-reduce-you-html-output-in-11ty-ec0c358be2ac), or from one of our other 11ty sites:

```js
const htmlmin = require('html-minifier');
  
 //...

    eleventyConfig.addTransform('htmlmin', (content, outputPath) => {
      if (outputPath.endsWith('.html')) {
        let minified = htmlmin.minify(content, {
          collapseWhitespace: true,
          minifyCSS: true,
          minifyJS: true,
          removeComments: true
        });
        return minified;
      }
      return content;
    });
```

Suggest we perhaps do this for all environments, as opposed to just for `production`, just to get a better steer on any potential pitfalls or minification quirks during development.

This will boost TTFB of responses for the inital load of HTML pages. For example, the homepage should go from 17kb to 14kb. Every lil' helps on that first request.

**Comment by Pete-Robelou** [comment]
Done.

I was a little unsure about running it locally for dev as it could slow things down as it builds but I didn't notice any perceivable difference 🙂
