### ISSUE TITLE
`main` branch setup

### ISSUE THREAD

**Issue by adamduncan** [ceph/ceph.io#222]
Throughout our conversations around branching workflow, we've referred to both `master` and `main` branches synonymously. The repository's `master` branch is currently empty (albeit a placeholder README).

Decision on today's call was that we'd have a `main` branch going forward in favour of `master`.

@djgalloway Are you able to please set this up, and ensure it's the primary branch for the repository? This will be what we'll be looking to merge to from `develop` when we're ready to go live tomorrow.

Based on [this commit](https://github.com/ceph/ceph-build/pull/1848/files#diff-1724c605918437a14d794d62a10d7d5c6bc1362de8ee108c11713c19bac014feR16), I expect the build/deploy config is already set up to support `main`? That PR will need merging too?

Thanks!

**Comment by djgalloway** [comment]
![Screenshot at 2021-06-22 11-26-24](https://user-images.githubusercontent.com/11281208/122953477-c02bc000-d34c-11eb-85fd-63966647e9a6.png)
