### ISSUE TITLE
jenkins render markdown view for .md files

### ISSUE THREAD

**Issue by ideepika** [ceph/ceph.io#237]
would be nice to have something similar to the one we have for ceph/ceph  as `jenkins render docs`

**Comment by idryomov** [comment]
@djgalloway mentioned that if you push a wip-foo branch to this repo, the preview should be available at wip-foo.ceph.io.

**Comment by djgalloway** [comment]
Yep. e.g., https://14222.ceph.io/en/news/blog/2021/v14-2-22-nautilus-released/
