### ISSUE TITLE
Page: Solutions / Case studies (category)

### ISSUE THREAD

**Issue by adamduncan** [ceph/ceph.io#24]
- [x] TBC on page title. Currently **Category "Commerce"** — Suggest: just  **Commerce** (as we are signposted by nav) or **Case studies: Commerce**
- [x] Add Category `select` control for quick access between categories

**Comment by Pete-Robelou** [comment]
Done.

I've followed the [design for the blog category page](https://projects.invisionapp.com/share/D8Z2N4X7U6J#/screens/433224559) as we don't have a specific design and this shows the page title and the filter by heading.

We need content for the `Subscribe to Ceph Announcements` panel at the bottom.
