### ISSUE TITLE
Off-by-one issue with dates

### ISSUE THREAD

**Issue by adamduncan** [ceph/ceph.io#241]
As [documented here](https://www.11ty.dev/docs/dates/#dates-off-by-one-day), we have an off-by-one issue with dates on the site when its built on the build server.

A date set on a Blog or Tech talk, for example, may be set as `date: '2021-06-21'`, but by the time they go through Eleventy and our `formatDate` filter, come out as `Jun 20, 2021`.

E.g. https://github.com/ceph/ceph.io/pull/231/files#diff-b2b3dd3402c3837930bf6907a1dd2607cb54ea0153f9c357d82722ca93933829R3 and https://ceph.io/en/news/blog/2021/ceph-foundation-announces-the-formation-of-the-ceph-market-development-group/

Have tried a few fixes to resolve this ([f582e8d](https://github.com/ceph/ceph.io/pull/239/commits/f582e8dc2d2b4219ba5a126efd8b52c9f83abf2b), [39602e0](https://github.com/ceph/ceph.io/pull/239/commits/39602e0a5b04885a64ca4ec06e1b5511df4fe11b), [1e2d125](https://github.com/ceph/ceph.io/pull/239/commits/1e2d1257e9126d910847e74514cc98cdb68cb99c), but none have had the intended effect.

Suggest we want to look deeper into UTC time and the build server.

cc @Pete-Robelou

**Comment by djgalloway** [comment]
I can easily change the timezone of the website to UTC.  It should've been from the start IMO.

**Comment by djgalloway** [comment]
I changed the website to UTC and restarted nginx.  Still behind a day :man_shrugging: https://ceph.io/en/news/blog/2021/v14-2-22-nautilus-released/

**Comment by adamduncan** [comment]
Thanks @djgalloway, that certainly helps make working with dates more predictable.

I've implemented a fix and PR'd #242, which fixes the dates. Happy for you to confirm and merge 👍

**Comment by adamduncan** [comment]
Closing based on fix from update to server timezone
