### ISSUE TITLE
Include GIF handling in image processing script

### ISSUE THREAD

**Issue by adamduncan** [ceph/ceph.io#243]
Currently we only support processing of jpg, png and svg.

We also need to support `gif`. I expect we'll need to update the `scripts/images.js` build task to include this extension, and make use of `imagemin-gifsicle` or similar.

See current PR in need of this support: https://github.com/ceph/ceph.io/pull/236

**Comment by Pete-Robelou** [comment]
All done.

I set the number of colours to `96`, this offers a reasonable level of compression without degrading the image too much. Our mileage will vary a bit though depending on the image, ideally we need to encourage the use of `jpg` for photography and `png` for everything else.

There is also `webp` but that's a discussion for another day 🙂
