### ISSUE TITLE
Page: Solutions / Case study

### ISSUE THREAD

**Issue by adamduncan** [ceph/ceph.io#25]
Resources:
- [Design 1](https://projects.invisionapp.com/share/D8Z2N4X7U6J#/screens/432974001)

**Comment by Pete-Robelou** [comment]
I've implemented the layout as per the design while using lorem ipsum content and placeholder assets.

Once we have proper assets I'll need to loop back to the sponsor logos etc...

I've also left the `html` snippet  for the numerical stats at the bottom in the `.md`. We'll need to assess how we wanna proceed with these, i.e. Macros, shortcodes or baked directly into the layout and data driven from frontmatter.

I've also taken a crack at a README.md to document how to we administer the case studies. Let me know what you think?
It'll be a massive time saver if we can land on a structure that can be replicated without too many bespoke amendments.

cc @adamduncan

**Comment by Pete-Robelou** [comment]
This has the same consideration for the hero image as mentioned on #44
