### ISSUE TITLE
Blog post: Missing detailed images

### ISSUE THREAD

**Issue by sebastian-philipp** [ceph/ceph.io#251]
https://ceph.io/en/news/blog/2018/new-dashboard-landing-page-nautilus-merged/ points to 

`https://ceph.com/wp-content/uploads/2018/09/dashboard-landing-page-before.png`

![](https://ceph.com/wp-content/uploads/2018/09/dashboard-landing-page-before.png)

and 

`https://ceph.com/wp-content/uploads/2018/09/landing-page-2018-08-17.png`

![](https://ceph.com/wp-content/uploads/2018/09/landing-page-2018-08-17.png)

but the images are missing

**Comment by djgalloway** [comment]
@adamduncan I'm going to fix this by just copying over the full images and changing the link to point to them

BUT

Is there a nice way of clicking the image and having it beautifully or more gracefully expanding to fill the browser window instead of just linking directly to the raw image?

**Comment by adamduncan** [comment]
Thanks @djgalloway. 

Yeah, the images being wrapped in links to themselves was a hangover from the WordPress export. I presume that wasn't something that could be automated out of the initial import.

> Is there a nice way of clicking the image and having it beautifully or more gracefully expanding to fill the browser window instead of just linking directly to the raw image?

It wasn't a feature of the initial design, but worth raising as a feature request if it's something that users are after? E.g. I expect we'd want to write our own enhancement (similar to [plugins out there](https://rpearce.github.io/image-zoom/?path=/story/react-medium-image-zoom--img) to work on this particular style of WP links containing images in the blog post template only)
