### ISSUE TITLE
Page: Users / Training & professional services

### ISSUE THREAD

**Issue by adamduncan** [ceph/ceph.io#26]
Resources:
-[Design](https://projects.invisionapp.com/share/D8Z2N4X7U6J#/screens/432974002)

**Comment by Pete-Robelou** [comment]
@adamduncan I've looked through the supplied content docs but can't find anything for this page.

Shall I can create it with lorem ipsum for now based on the design?

**Comment by Pete-Robelou** [comment]
This page has now been moved to `/users/training-professional-services/` but it still needs content.

See #123 for IA restructure.
