### ISSUE TITLE
Page: Developers

### ISSUE THREAD

**Issue by adamduncan** [ceph/ceph.io#27]
Resources:
- [Design](https://projects.invisionapp.com/share/D8Z2N4X7U6J#/screens/432974003)

**Comment by Pete-Robelou** [comment]
Done.

I've added content from the supplied docs so it can all be reviewed within the context of the design. It is a little bit light in comparison to the design so I've tried to match it as best I could and I've filled the additional parts of the design with lorem ipsum for now. 

- [ ] Replace lorem ipsum copy
- [ ] Check all link locations
- [ ] Need billboard image
- [ ] Check logos for all cards and replace if necessary
