### ISSUE TITLE
Community calendar iframe doesn't seem to render properly

### ISSUE THREAD

**Issue by dabukalam** [ceph/ceph.io#297]
Tested in Chrome and Firefox on MacOS and neither work for me. Maybe it's just a calendar permissions thing?

<img width="926" alt="Screenshot 2021-11-02 at 17 27 23" src="https://user-images.githubusercontent.com/5021691/139879096-ecefc928-7ead-42a0-86b9-cdb38d454c5c.png">

**Comment by adamduncan** [comment]
PR in progress at #320
