### ISSUE TITLE
Unresponsive behavior of image in slider

### ISSUE THREAD

**Issue by aryan7778** [ceph/ceph.io#3]
2nd image in the slider is showing unresponsive behavior.
Is the source code of this website is not public?

**Comment by jasonvds** [comment]
@aryan7778 this repo is for the website currently under development, not the live website which is hosted and maintained separately.

**Comment by adamduncan** [comment]
Closing this as an old issue with the legacy site. 

Going live with the new site at ceph.io today 👍
