### ISSUE TITLE
Blog entries can be accessed from multiple site paths

### ISSUE THREAD

**Issue by Thingee** [ceph/ceph.io#334]
Blog entries can be accessed from /community and contain broken images. For example, this entry:

https://ceph.io/community/bluestore-default-vs-tuned-performance-comparison/

https://ceph.io/en/news/blog/2019/bluestore-default-vs-tuned-performance-comparison/

The expected behavior would be for blog entries to only be accessed from /en/news/blog.

**Comment by adamduncan** [comment]
This could be related to the [`redirects`](https://github.com/ceph/ceph.io/blob/main/ansible/roles/deploy/templates/redirects.j2) in place for the site. The static files generated for the site don't duplicate any blog pages in the `community` section. Also, the redirects [don't yet include 2022](https://github.com/ceph/ceph.io/blob/main/ansible/roles/deploy/templates/redirects.j2#L167), for example, so we don't see the same true of posts from this year, e.g. https://ceph.io/community/cephalocon-postponed/

@Thingee As you say, the correct URL is the latter (`/en/news/blog/...`). We include a `<link rel="canonical">` meta tag to ensure this remains the case, and is what is indexed by search and search engines.

I wonder if we'd be able to revisit the rewrite rules to tighten the scope of what's applied? @djgalloway Or if we're confident that the new site's been live long enough for referrer sites to correct any old links (and search engines to re-index), we could consider retiring some of the old redirects. Hope that helps 👍

**Comment by djgalloway** [comment]
https://github.com/ceph/ceph.io/pull/340 fixes this
