### ISSUE TITLE
Page: Community

### ISSUE THREAD

**Issue by adamduncan** [ceph/ceph.io#34]
Resources:
- [Design](https://projects.invisionapp.com/share/D8Z2N4X7U6J#/screens/432973997)

**Comment by Pete-Robelou** [comment]
Done.

I've added content from the supplied docs so it can all be reviewed within the context of the design. It is a little bit different in comparison to the design so I've tried to match it as best I could but I've left out the `connect` and `team` paragraphs as it would have created an uneven amount of cards within the `Connect with the Ceph community` section. 

- [ ] Check matrix modules content
- [ ] Check all link locations
- [ ] Check logos for all cards and replace if necessary

We could consider sweeping away some of the sections like `upcoming events` and `featured tech talks` into includes.
