### ISSUE TITLE
Page: Community / Event

### ISSUE THREAD

**Issue by adamduncan** [ceph/ceph.io#36]
Resources:
- [Design 1](https://projects.invisionapp.com/share/D8Z2N4X7U6J#/screens/432974005)
- [Design 2](https://projects.invisionapp.com/share/D8Z2N4X7U6J#/screens/432974006)

**Comment by Pete-Robelou** [comment]
All done.

This has the same consideration for the hero image as mentioned on #44

I've implemented some logic so the `register` button only appears for future events and the `video/slide` links only appear on past events.
