### ISSUE TITLE
Add more info about Foundation Members

### ISSUE THREAD

**Issue by dvanders** [ceph/ceph.io#363]
It would be nice to see more information about the foundation members, e.g. describe how the members are using or providing services based on Ceph.

**Comment by akoolarni** [comment]
@dvanders 
Assign me this issue please.

**Comment by akoolarni** [comment]
Will try to to incorporate

**Comment by akoolarni** [comment]
@dvanders thank you for assigning this to me.
Firstly, where can I find the info that has to be added.
Or the information valuable for displaying? 
Would be greatful if you help me in this.

**Comment by akoolarni** [comment]
Hello this issue is already completed. 
Please close this issue

**Comment by gauravsitlani** [comment]
Closing this issue based on https://github.com/ceph/ceph.io/issues/363#issuecomment-2001916782
