### ISSUE TITLE
Page: Community / Tech talks

### ISSUE THREAD

**Issue by adamduncan** [ceph/ceph.io#37]
We don't have a specific design so I've followed a similar layout to the current [ceph site](https://ceph.io/ceph-tech-talks/).

**Comment by Pete-Robelou** [comment]
Done.

I've added content from the supplied docs so it can all be reviewed within the context of the design. 

I've grabbed the other content from the [ceph.io site](https://ceph.io/ceph-tech-talks/).

- [ ] Check all links
