### ISSUE TITLE
Page: Community / Community events & meetups

### ISSUE THREAD

**Issue by adamduncan** [ceph/ceph.io#38]
We don't have a specific design so I've followed a similar layout to the current site influenced by the latest wireframe.

- [x] Rename to `Community events & meetups`

Resources:
- [Existing page on ceph.io](https://ceph.io/community/meetings/)

![Ceph Wireframes v9 002](https://user-images.githubusercontent.com/13508865/110509599-2ec87300-80fa-11eb-9f2b-08f1d1b7a687.jpeg)

**Comment by Pete-Robelou** [comment]
Done.

I've added [content from the existing site](https://ceph.io/community/meetings/) so it can all be reviewed within the context of the design. 

- [ ] Check all links
