### ISSUE TITLE
Page: News

### ISSUE THREAD

**Issue by adamduncan** [ceph/ceph.io#41]
Resources:
- [Design](https://projects.invisionapp.com/share/D8Z2N4X7U6J#/screens/432973998)

**Comment by Pete-Robelou** [comment]
Done.

I've added content from the supplied docs so it can all be reviewed within the context of the design.

- [ ] Check matrix modules content
- [ ] Check all link locations
- [ ] Replace placeholder images
- [ ] Check logos for all cards and replace if necessary
