### ISSUE TITLE
Ceph pool gets stuck in updating state in the dashboard. 

### ISSUE THREAD

**Issue by powerpratik** [ceph/ceph.io#430]
Hello,
 I have a running ceph three-node cluster with 3 monitors. The full service and the cluster information is available in the dashboard image attached.
![Screenshot from 2022-08-11 15-27-54](https://user-images.githubusercontent.com/25316608/184223720-1c3eae63-7958-4dae-a729-451d2e1f9117.png)
 I was able to create OSDs through dashboard prompts and also via the command line. But out of the three nodes(caas-s1,caas-s2,caas-s3) only the drives on the third node gets added even though the OSD drives for the other two are shown in the OSD addition prompts and the addition of the OSD does not result in any errors. 
Add device prompt while adding OSD via dashboard is shown below.
![Screenshot from 2022-08-11 15-37-30](https://user-images.githubusercontent.com/25316608/184224974-d1cae0f4-0666-495d-bb2c-82bfa2612e49.png)

As a result of this, when I try to create a new pool, the pool gets created but is getting stuck in the updating state. Image attached below.
![Screenshot from 2022-08-09 10-28-31](https://user-images.githubusercontent.com/25316608/184226229-9112377d-0651-48ce-9281-5bbe5e47c8fe.png)

 Here is the ceph full health detail when the pool has been added and gets stuck in the updating state. 
[health_detail.log](https://github.com/ceph/ceph.io/files/9311595/health_detail.log)

**Comment by Thingee** [comment]
@powerpratik Hi, this is to report issues for the ceph website. If you would like to report the problems for the Ceph project itself, please go to https://tracker.ceph.com/projects/ceph
