### ISSUE TITLE
Ceph OSD addition failure 

### ISSUE THREAD

**Issue by powerpratik** [ceph/ceph.io#431]
Hi,
I have a 3 node ceph cluster and 5 osds for the hosts. I am trying to add more OSDs as i have available disks. The ceph orch device ls comand views the disks as available and there is no reject reasons for the new disks. Image is below:
![Screenshot from 2022-08-12 12-20-41](https://user-images.githubusercontent.com/25316608/184400434-4a2a841d-c888-4ddb-8f50-c82ecc64760b.png)

But when i try to add osds from caas-s1 node using  " sudo ceph orch daemon add osd caas-s1:/dev/sdc ",  it gives me an error (** ERROR: error creating empty object store in /var/lib/ceph/osd/ceph-5/: (13) Permission denied)  that does not add the osds on to the cluster. 
The log for that is available below:
[health_log.log](https://github.com/ceph/ceph.io/files/9328646/health_log.log)
Any help will be appreciated.

**Comment by Thingee** [comment]
@powerpratik Hi, this is to report issues for the ceph website. If you would like to report the problems for the Ceph project itself, please go to https://tracker.ceph.com/projects/ceph
