### ISSUE TITLE
Page: News / Blog article

### ISSUE THREAD

**Issue by adamduncan** [ceph/ceph.io#44]
Resources:
- [Design](https://projects.invisionapp.com/share/D8Z2N4X7U6J#/screens/432974009)

**Comment by Pete-Robelou** [comment]
All done.

One thing I noticed was an aspect ratio descrepancy with some of the images on the currently populated blog posts. We've setup our hero image to be 16x9 so when it receives an image that's not 16x9 it will either be cropped if we use `object-fit: cover` or have borders top/bottom if we use `object-fit: contain`. It's not a deal breaker but something to keep in mind.

**Comment by adamduncan** [comment]
Good point re: aspect ratios. We'll have to see what we're working with across the blog posts that migrate over. We're bound to have a lot without images, and those that do could be varied in their ratios.

If it's unrealistic to shoehorn legacy content into the 16:9 container on the article pages, we might have to consider leaving those images free of their media-wrap constraints.

**Comment by Pete-Robelou** [comment]
> Good point re: aspect ratios. We'll have to see what we're working with across the blog posts that migrate over. We're bound to have a lot without images, and those that do could be varied in their ratios.
> 
> If it's unrealistic to shoehorn legacy content into the 16:9 container on the article pages, we might have to consider leaving those images free of their media-wrap constraints.

Agreed, let's see what assets comes through during content population. It'll be a shame to lose the `lazy loading` that comes with the media-wrap but it's not a deal break as the hero image is unlikely to need it and all the other assets will be within `richtext` so wouldn't be lazy loaded anyway.

We do need to keep in mind the images needed for the cards that appear on listing pages. We currently have a fallback placeholder built into the cards so if a blog post doesn't have an image we'll still see something in the card but this needs some consideration. This issue will apply to blog posts, case studies, events and press releases.

Will there be a pool of generic assets that we can use to populate cards when no image is supplied?

**Comment by adamduncan** [comment]
>  It'll be a shame to lose the lazy loading that comes with the media-wrap

I think even if we don't use the media-wrap, we can still apply `loading="lazy"` to the hero images as templated.

> Will there be a pool of generic assets that we can use to populate cards when no image is supplied?

We need to discuss this in terms of design and production of these, but it's been [flagged](https://docs.google.com/spreadsheets/d/1HM6g0YDHxaNsBam9wzDPeCrmaW7zR1MKEY2xBuc_1II/edit#gid=0&range=L40) as a point to resolve, yep.
