### ISSUE TITLE
Expired cert for ceph.io

### ISSUE THREAD

**Issue by mazzystr** [ceph/ceph.io#469]
Looks like your Let's Encrypt process isn't working.  The cert expired Fri, 11 Nov 2022 20:19:21 GMT

**Comment by idryomov** [comment]
@dmick, @akraitman PTAL

**Comment by idryomov** [comment]
> Already fixed

What is the process there?  Is it a manual action, is there an alert?  Just want to avoid someone running into this again in three months (Fri, 10 Feb 2023)...

**Comment by dmick** [comment]
some are supposed to be automatic, but fail for reasons I haven't diagnosed.  Some are manual because they require a webserver restart and it was desired to schedule that/supervise it.  Alerts are supposed to happen, but are not universal, and I'm tracking that down.

**Comment by mazzystr** [comment]
Thanks!
