### ISSUE TITLE
Page: Foundation

### ISSUE THREAD

**Issue by adamduncan** [ceph/ceph.io#50]
We don't have a specific design so infer from content and use components from other landing pages.

Resources:
- [Designs](https://projects.invisionapp.com/share/D8Z2N4X7U6J#/screens/433505643?browse)

**Comment by Pete-Robelou** [comment]
Done.

I've added content from the supplied docs so it can all be reviewed within the context of the design. The content doc has 5 chunks of copy so I've used a selection of layouts from other landing pages to best fit the content.

- [ ] Check all link locations
- [ ] Replace placeholder images
- [ ] Replace lorem ipsum headings
- [ ] Check icons for all cards and replace if necessary
