### ISSUE TITLE
CSP for third-party webfont files

### ISSUE THREAD

**Issue by adamduncan** [ceph/ceph.io#64]
Noticed the request for our third-party webfont (Google Fonts) wasn't loading on the develop site. Looks to be related to be CSP.

```Content Security Policy: The page's settings blocked the loading of a resource at https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap ("style-src").```

@djgalloway Curious: Is this a policy it makes sense/is best to put in place as part of our existing configuration? Can see some references to it in the ansible config.

**Comment by djgalloway** [comment]
https://github.com/ceph/ceph.io/pull/66

**Comment by adamduncan** [comment]
Always super helpful. Thanks @djgalloway
