### ISSUE TITLE
"I modified the erasure code configuration, causing the OSD to fail to start. What should I do?"

### ISSUE THREAD

**Issue by niklaus-code** [ceph/ceph.io#759]
1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x135) [0x555a36c45631]
 2: /usr/bin/ceph-osd(+0x5977f7) [0x555a36c457f7]
 3: (ECBackend::continue_recovery_op(ECBackend::RecoveryOp&, RecoveryMessages*)+0x1e30) [0x555a3719e8b0]
 4: (ECBackend::handle_recovery_read_complete(hobject_t const&, boost::tuples::tuple<unsigned long, unsigned long, std::map<pg_shard_t, ceph::buffer::v15_2_0::list, std::less<pg_shard_t>, std::allocator<std::pair<pg_shard_t const, ceph::buffer::v15_2_0::list> > >, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type>&, std::optional<std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, ceph::buffer::v15_2_0::list, std::less<void>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, ceph::buffer::v15_2_0::list> > > >, RecoveryMessages*)+0x4c2) [0x555a3719f052]
 5: (OnRecoveryReadComplete::finish(std::pair<RecoveryMessages*, ECBackend::read_result_t&>&)+0x71) [0x555a371c4e21]
 6: (ECBackend::complete_read_op(ECBackend::ReadOp&, RecoveryMessages*)+0x8d) [0x555a3718f88d]
 7: (ECBackend::handle_sub_read_reply(pg_shard_t, ECSubReadReply&, RecoveryMessages*, ZTracer::Trace const&)+0xd1c) [0x555a371aaf4c]
 8: (ECBackend::_handle_message(boost::intrusive_ptr<OpRequest>)+0x2d4) [0x555a371aba24]
 9: (PGBackend::handle_message(boost::intrusive_ptr<OpRequest>)+0x56) [0x555a36f5e2c6]
 10: (PrimaryLogPG::do_request(boost::intrusive_ptr<OpRequest>&, ThreadPool::TPHandle&)+0x512) [0x555a36ef09f2]
 11: (OSD::dequeue_op(boost::intrusive_ptr<PG>, boost::intrusive_ptr<OpRequest>, ThreadPool::TPHandle&)+0x1c0) [0x555a36d46900]
 12: (ceph::osd::scheduler::PGOpItem::run(OSD*, OSDShard*, boost::intrusive_ptr<PG>&, ThreadPool::TPHandle&)+0x6d) [0x555a370452ad]
 13: (OSD::ShardedOpWQ::_process(unsigned int, ceph::heartbeat_handle_d*)+0x115f) [0x555a36d59dbf]
 14: (ShardedThreadPool::shardedthreadpool_worker(unsigned int)+0x435) [0x555a374b78c5]
 15: (ShardedThreadPool::WorkThreadSharded::entry()+0x14) [0x555a374b9fe4]
 16: /lib64/libpthread.so.0(+0x81cf) [0x7f298180f1cf]
 17: clone()

**Comment by ljflores** [comment]
Hey @niklaus-code, you can raise a tracker for this on tracker.ceph.com.
