### ISSUE TITLE
Making the About section more informative

### ISSUE THREAD

**Issue by olliefr** [ceph/ceph.io#9]
The `About ` section of this repository currently states the following.

> This repo contains static site content for www.ceph.io

Since there is no pull requests for repository metadata (tell me if I'm wrong on this?), I am filing an issue to update the `About` section to the following text.

`This repo contains files for the new version of www.ceph.io, currently under development. For information on the current version of the website, please see the README file.`

Or something along this line to:

1. State clearly that this repo is not for the current website.
2. Provide directions to those seeking the repo or contact info for the current website.

This would stop confusion, such as issue #3, as well as provide a clear route for people willing to contribute (as I were, but could not find how).

**Comment by adamduncan** [comment]
Looks like this landed in #8 with helpful info now in README.

Happy to close, @olliefr?

**Comment by olliefr** [comment]
Yes, thank you for your time and effort! 🙃
